### ISSUE TITLE
Cannot use too much division and power square

### ISSUE THREAD

**Issue by Junzeng-x14** [yalmip/YALMIP#654]
Hello!

I encountered a small issue about cost function building. For example,
```
x = sdpvar(1);
cost = (x/50)^8;
```
Then it will fail and say that
```
Unable to perform assignment because dot indexing is not supported for variables of this type.
Error in  ^  (line 146)
    y.extra.createTime = definecreationtime;
```
Currently I hacked it as `cost = x^8/(50^8)`, maybe an editing in `mpower.m` would be helpful for future users.

Thank you!

**Comment by johanlofberg** [comment]
ok.

for your information, the reason this occurs is that the coefficient becomes so small that yalmip considers it to be 0 (although that does not happen in the second version due to different tolerances in cleaning up expressions). this means you cannot expect any optimization work robustly when you have a model involving these terms, it drowns in numerical noise and floating-point tolerances

**Comment by Junzeng-x14** [comment]
> ok.
> 
> for your information, the reason this occurs is that the coefficient becomes so small that yalmip considers it to be 0 (although that does not happen in the second version due to different tolerances in cleaning up expressions). this means you cannot expect any optimization work robustly when you have a model involving these terms, it drowns in numerical noise and floating-point tolerances

Yep, the error comes from that the coefficient is so small.
