### ISSUE TITLE
How to remove the kitten image when running sdpsettings statement

### ISSUE THREAD

**Issue by Pei-w** [yalmip/YALMIP#898]
Which cat picture is very cute, I also like it very much, but the program I run needs to loop d to call the `sdpsettings` in yalmip. Is there any way for a friend to help me **remove the cat picture temporarily**? If this question can be answered, I will be very grateful

**Comment by johanlofberg** [comment]
sdpsettings is not in any sense related to the abused kitten.

The only sensible way to remove the cat is to fix the underlying problem with strict inequalities

https://yalmip.github.io/inside/strictinequalities/

...or you install the develop version where the cat is gone, but that's because strict inequalities are removed completely from the language

**Comment by johanlofberg** [comment]
Btw, as this is not an issue with the code but more of a usage question, I've converted this to a thread in the discussions instead
